### ISSUE TITLE
hubble-grpc.kube-system.svc.cluster.local

### ISSUE THREAD

**Issue by Ruilkyu** [cilium/hubble#252] opened 2020-04-30 09:11 UTC
"err":{"message":"getaddrinfo EAI_AGAIN hubble-grpc.kube-system.svc.cluster.local","locations"

**Comment by Rolinh** [comment] 2020-04-30 09:26
I assume this is a bug report? Information about the context in which this occurs, the version of hubble this affects and how hubble was deployed would help. I'll close this issue for now as we can't do much on our end with so little information.

**Comment by Ruilkyu** [comment] 2020-04-30 10:00
git clone https://github.com/cilium/hubble.git --branch v0.5
cd hubble/install/kubernetes


helm template hubble \
    --namespace kube-system \
    --set metrics.enabled="{dns:query;ignoreAAAA;destinationContext=pod-short,drop:sourceContext=pod;destinationContext=pod,tcp,flow,port-distribution,icmp,http}" \
    --set ui.enabled=true \
    > hubble.yaml

**Comment by Rolinh** [comment] 2020-05-05 19:49
Closing as duplicate of #180

**Closed by Rolinh** 2020-05-05 19:49 UTC
