### ISSUE TITLE
helm charts pointing to tag "latest"

### ISSUE THREAD

**Issue by aanm** [cilium/hubble#198] opened 2020-03-23 11:45 UTC
It seems the helm charts are pointing to tag "latest". We should pin it to a specific version and change the image pull policy to `IfNotPresent`

```
                        "image": "quay.io/cilium/hubble:latest",
                        "imagePullPolicy": "Always",
```

**Comment by gandro** [comment] 2020-03-23 11:47
Duplicate of #71

**Closed by gandro** 2020-03-23 11:47 UTC
Labels: 🐛 kind/bug
