### ISSUE TITLE
Hubble UI: websocket connection failed 

### ISSUE THREAD

**Issue by fafucoder** [cilium/hubble#339] opened 2020-08-11 08:38 UTC
![image](https://user-images.githubusercontent.com/16442491/89875915-76346280-dbf0-11ea-9812-de3372f75f1d.png)

![image](https://user-images.githubusercontent.com/16442491/89877092-2e163f80-dbf2-11ea-965e-ae68d15651da.png)

Follow the [hubble-ui](https://github.com/cilium/hubble-ui) guide, `npm run watch` in server and `npm run start` in client, but when fresh localhost:12000, the server return websock connect ECONNRESET error

My environment is:
- `node: v14.4.0`
- `npm: v6.14.5`

**Comment by fafucoder** [comment] 2020-08-11 08:43
![image](https://user-images.githubusercontent.com/16442491/89876738-a7616280-dbf1-11ea-9964-4ded0004f780.png)


When i notes the websock proxy, it's work success!  what this problem?

**Comment by gandro** [comment] 2020-08-17 15:34
Thanks for the report @fafucoder! Are you using L7 policies or visibility annotations that apply to the hubble-ui pod? In that case, this might be a duplicate of https://github.com/cilium/cilium/issues/11672

**Comment by geakstr** [comment] 2021-05-11 14:39
Shouldn't be related to newer versions. Closing

**Closed by geakstr** 2021-05-11 14:39 UTC
Labels: 🖥 area/ui
