### ISSUE TITLE
Install Hubble from installation guide failing

### ISSUE THREAD

**Issue by amitrintzler** [cilium/hubble#101] opened 2020-02-13 07:42 UTC
Hi, 
when trying to follow the instructions that appears in this site:
https://github.com/cilium/hubble/blob/master/Documentation/installation.md
once you reach to hubble and try to run this cmd:
```
helm template hubble \
    --namespace kube-system \
    --set metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,http}" \
    > hubble.yaml
```

you will fail on :
```
Error: rendering template failed: runtime error: invalid memory address or nil pointer dereference
```

tried to install also without any metrics and also not working , it looks like the template that exist here not working .
can you please update the guidelines if any thing is expected?

**Comment by Rolinh** [comment] 2020-02-13 07:56
Hi @amitrintzler, I can't reproduce. Are you sure you're running this command from the `hubble/install/kubernetes` directory? And which version of helm are you using?

**Comment by amitrintzler** [comment] 2020-02-13 08:10
Hi @Rolinh , 
Yes, helm v2.10.0

**Comment by Rolinh** [comment] 2020-02-13 08:24
I failed to reproduce with helm v2 (v2.16.1) as well.
Your helm version is 1.5 years old though, would you mind trying with a more recent one?

**Comment by amitrintzler** [comment] 2020-02-13 08:25
Hi, 
my application still using this helm version so cant upgrade it for now.
is there any thing specific that i can provide to assist you reproduce?
i'm running it on VM that host in openstack

**Comment by Rolinh** [comment] 2020-02-14 17:16
If you're running a no longer maintained version of helm that contains a bug that prevents you from generating charts, I don't think there's much we can do on our end.

**Comment by genbit** [comment] 2020-02-14 22:20
@amitrintzler try to modify values.yaml instead of specifying 
```
--set metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,http}" \
```

**Comment by amitrintzler** [comment] 2020-02-16 07:37
Hi @genbit , 
i tried also without any metrics in the set part and also getting the same issue.
maybe i'm doing some thing wrong:
these are the steps:
1. curl -LO https://github.com/cilium/cilium/archive/v1.7.0-rc1.tar.gz
tar xzvf v1.7.0-rc1.tar.gz
cd cilium-1.7.0-rc1/install/kubernetes
2. helm template cilium \
  --namespace kube-system \
  --set global.tag=v1.7.0-rc1 \
  > cilium.yaml
kubectl create -f cilium.yaml

till here no issue
now:
git clone https://github.com/cilium/hubble.git
cd hubble/install/kubernetes
helm template hubble \
    --namespace kube-system \
    --set metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,http}" \
    > hubble.yaml

now i'm getting the error...

**Comment by michi-covalent** [comment] 2020-02-17 17:03
@genbit @Rolinh perhaps it makes sense to have a generated yaml file checked in somewhere like cilium does with `quick-install.yaml`? 

https://docs.cilium.io/en/v1.6/gettingstarted/minikube/#install-cilium

**Comment by michi-covalent** [comment] 2020-02-17 17:15
@amitrintzler in the meantime you can use this yaml file:

[hubble.yaml.txt](https://github.com/cilium/hubble/files/4215186/hubble.yaml.txt)

**Comment by amitrintzler** [comment] 2020-02-17 17:24
Hi Guys,
Many thanks for your support!
To be sure i will not do any mistake:
You want me to do the following,
Instead this one:
git clone https://github.com/cilium/hubble.git
cd hubble/install/kubernetes
helm template hubble 
--namespace kube-system 
--set metrics.enabled="{dns,drop,tcp,flow,port-distribution,icmp,http}" 
> hubble.yaml

What should i have that will work with the metrics?

**Comment by michi-covalent** [comment] 2020-02-17 17:29
@amitrintzler you can either download hubble.yaml.txt or apply it directly:
```
kubectl apply -f https://github.com/cilium/hubble/files/4215186/hubble.yaml.txt
```
i generated this file using the command:
```
        helm template hubble \
            --namespace kube-system \
            --set metrics.enabled="{dns:query,drop,tcp,flow,port-distribution}" \
            > hubble.yaml
```
so it should have the metrics enabled.

**Comment by genbit** [comment] 2020-02-17 17:51
there is also - https://github.com/cilium/hubble/blob/master/tutorials/deploy-hubble-servicemap/hubble-all-minikube.yaml

**Comment by michi-covalent** [comment] 2020-02-18 04:51
@genbit yeah let's just use that. is there anything minikube specific about the yaml file?

**Comment by genbit** [comment] 2020-02-18 15:46
> @genbit yeah let's just use that. is there anything minikube specific about the yaml file?

not really, should be good to use for other installations as well

**Comment by michi-covalent** [comment] 2020-02-18 15:54
@genbit there is still a pending pr for this

**Closed** 2020-02-20 17:19 UTC
