### ISSUE TITLE
Error: 14 UNAVAILABLE: failed to connect to all addresses

### ISSUE THREAD

**Issue by efenex** [cilium/hubble#15] opened 2019-11-21 13:56 UTC
After deploying cilium and hubble onto a GKE setup, I get the following error in the hubble ui (for the servicemap):

Failed to discover cluster: Error: from hubble: Error: 14 UNAVAILABLE: failed to connect to all addresses

The logs for the hubble-ui pod:

{"name":"frontend","hostname":"hubble-ui-548f6dfc9-czss8","pid":18,"req_id":"88ea14bc-662c-439e-9bb1-dc29c3d55575","user":"admin@localhost","level":50,"err":{"message":"from hubble: Error: 14 UNAVAILABLE: failed to connect to all addresses","locations":[{"line":10,"column":7}],"path":["viewer","discoverCluster"],"extensions":{"code":"INTERNAL_SERVER_ERROR"}},"msg":"","time":"2019-11-21T13:53:52.745Z","v":0}

Hubble pods themselves:

{"level":"info","ts":1574338921.8148355,"caller":"cmd/server.go:166","msg":"Started server with args","max-flows":131071,"duration":0}
{"level":"info","ts":1574338921.8151586,"caller":"api/registry.go:73","msg":"Configured metrics plugin","name":"flow","status":""}
{"level":"info","ts":1574338921.8152533,"caller":"api/registry.go:73","msg":"Configured metrics plugin","name":"port-distribution","status":""}
{"level":"info","ts":1574338921.815333,"caller":"api/registry.go:73","msg":"Configured metrics plugin","name":"icmp","status":""}
{"level":"info","ts":1574338921.8154128,"caller":"api/registry.go:73","msg":"Configured metrics plugin","name":"http","status":""}
{"level":"info","ts":1574338921.8155031,"caller":"api/registry.go:73","msg":"Configured metrics plugin","name":"dns","status":""}
{"level":"info","ts":1574338921.8155766,"caller":"api/registry.go:73","msg":"Configured metrics plugin","name":"drop","status":""}
{"level":"info","ts":1574338921.8156652,"caller":"api/registry.go:73","msg":"Configured metrics plugin","name":"tcp","status":""}
{"level":"info","ts":1574338921.8190467,"caller":"cmd/server.go:286","msg":"Starting gRPC server on client-listener","client-listener":"unix:///var/run/hubble.sock"}
{"level":"warn","ts":1574338921.8237007,"caller":"server/ipcache.go:115","msg":"Failed to obtain IPCache from Cilium. If you are using Cilium 1.6 or older, this is expected. Pod names of endpoints running on remote nodes will not be resolved."}

Note that metrics in Grafana are working perfectly.

Also note that I am using kubectl port-forward to connect to the UI (this is not a minikube setup) and so I do not have access to the internal services - is that a requirement?

**Comment by gandro** [comment] 2019-11-21 15:41
Thanks for the report!

Looking at the log output, it seems like Hubble is not listening on the TCP port that UI accesses. Did you deploy Hubble using our Helm chart or did you use `tutorials/deploy-hubble-servicemap/hubble-all-minikube.yaml`?

If you deployed via Helm, I think I found the cause: It looks like our Helm chart does not enable the TCP port when `ui.enabled=true`. If you use the following Helm command (note the `listenClientUrls`), does it work for you?

    helm template hubble \                                  
        --namespace kube-system \
        --set metrics.enabled="{dns:query,drop,tcp,flow,port-distribution}" \
        --set listenClientUrls='{0.0.0.0:50051,unix:///var/run/hubble.sock}' \
        --set ui.enabled=true > hubble.yaml

**Comment by gandro** [comment] 2019-11-21 19:19
@efenex We've just merged PR #16 which fixes an issue in the Helm chart (if you deployed Hubble via Helm). Please let us know if this fixed the issue for you.

**Comment by genbit** [comment] 2019-11-27 23:37
I tried to reproduce it, and looks like issue is fixed.

**Closed by genbit** 2019-11-27 23:37 UTC
Labels: bug
